language: python

before_script: pip install docker-compose
script:
  # since there's a dependency on mongo, it will build that image also
  # although we have not added any tests scenario
  - docker-compose run service-2 sh -c "pytest"

services:
    - docker

before_install:
    - docker-compose build  navrang125/devops_task1

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker-compose push navrang125/devops_task1
