sudo: required

services:
    - docker
    
before_script: pip install docker-compose
script:
  # although we have not added any tests scenario
  - docker-compose run service-2 sh -c "pytest"
  
  
before_install:
    - docker-compose build  navrang125/devops_task1

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker-compose push navrang125/devops_task1
