language: generic

services:
    - docker
    
before_install:
    - docker-compose build
   
after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker-compose push navrang125/devops_task1
